# Generated by Django 5.0.4 on 2024-05-05 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkoutDetails',
            new_name='WorkoutDetail',
        ),
    ]
