# Generated by Django 5.0.4 on 2024-05-09 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_rename_user_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
